[project]
name = "pyutil"
authors = [
  { name = "tpltnt", email = "tpltnt+pyutil@nkawtg.net" },
]
description = "a collection of utilities for Python programmers"
dynamic = ["version"]
readme = "README.rst"
license = "GPL-2.0-or-later"
license-files = [
    "COPYING.GPL",
    "COPYING.SPL.txt",
    "COPYING.TGPPL.rst",
]
requires-python = ">=3.10"
keywords = ["utilities", "twisted"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries",
]
dependencies = ["simplejson>=2.1.0"]

[project.urls]
"Homepage" = "https://github.com/tpltnt/pyutil"
"Bug Tracker" = "https://github.com/tpltnt/pyutil/issues"

[project.optional-dependencies]
jsonutil = ['simplejson >= 2.1.0']
randcookie = ['zbase32 >= 1.0']

[project.entry-points.'console_scripts']
randcookie = 'pyutil.scripts.randcookie:main'
tailx = 'pyutil.scripts.tailx:main'
lines = 'pyutil.scripts.lines:main'
randfile = 'pyutil.scripts.randfile:main'
unsort = 'pyutil.scripts.unsort:main'
verinfo = 'pyutil.scripts.verinfo:main'
try_decoding = 'pyutil.scripts.try_decoding:main'
passphrase = 'pyutil.scripts.passphrase:main'

[build-system]
requires = ["setuptools", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
pyutil = ["data/wordlist.txt"]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pyutil/_version.py"
versionfile_build = "pyutil/_version.py"
tag_prefix = ""
parentdir_prefix = "pyutil-"
